spring.application.name=windows-auth-proxy

server.port=8095

# ==========================================
# SPRING CLOUD GATEWAY CONFIGURATIE
# ==========================================

# 1. Route ID en Doel-URI (Echte backend op 8092)
spring.cloud.gateway.routes[0].id=security_service_route
spring.cloud.gateway.routes[0].uri=http://localhost:8092

# 2. Predicates: Match alles wat begint met /api/
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/**

# 3. Filters: Voeg de Windows-gebruikersnaam toe aan de HTTP-header
spring.cloud.gateway.routes[0].filters[0]=AddRequestHeader=X-Remote-User, #{principal?.name}

#######################################################################
# JWT Configuration Properties
#######################################################################

# 1. JWT Secret Key
# This must be a long, randomly generated, and base64-encoded string.
# DO NOT store a weak secret key like this in production.
# This value is used to sign (generate the signature for) and verify the JWT.
application.security.jwt.secret-key=²

# 2. JWT Expiration Time
# The validity period for the token, expressed in milliseconds.
# 86400000 ms = 24 hours.
application.security.jwt.expiration=86400000
# Define a unique identifier for the service that is meant to receive the JWT
#application.security.jwt.audience=security-webservice-api
application.security.jwt.audience=kUZ//O1rOpet

# A unique identifier for the current signing key
#application.security.jwt.key-id=my-signing-key-v1
application.security.jwt.key-id=7/NAdrZzAc7l

# Identifier for the client application (Authorized Party)
#application.security.jwt.authorized-party=my-web-client-id-12345
application.security.jwt.authorized-party=6rL4ZZHOKeHZ

# Custom field combining authorized party and context Feference
#application.security.jwt.azpacr.value=my-web-client-id-12345/MFA
application.security.jwt.azpacr.value=frOF6APh4ZaP

# Custom field for Request History or Session Hint (used by AAD/Entra ID)
application.security.jwt.request-history=0.AQABAQjE70v8vQ+1234

# Unique identifier for the tenant/directory
application.security.jwt.tenant-id=0.AQABAQjE70v8vQ+1234

# Version of the token format (e.g., used by Microsoft Identity platform)
application.security.jwt.token-version=1.0

# Custom field for Family Safety/Conditional Access flags
#application.security.jwt.xms-ftd=some_security_flag_value
application.security.jwt.xms-ftd=DlzespL9lwof
